# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-18 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endagaweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetworkDenominaton',
            new_name='NetworkDenomination',
        ),
    ]
